<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/Python-Notebook-Banners/Examples.png"  style="display: block; margin-left: auto; margin-right: auto;";/>
</div>

# Examples: Working with DataFrames

In this notebook, we cover how to manipulate, transform, and alter Pandas DataFrames.

## Learning objectives

* Know how to sort, filter, and group Pandas DataFrames.
* Understand how to create and delete columns in Pandas DataFrames.
* Know how to apply custom transformations to Pandas DataFrames.

## Introduction

When a dataset only has a few data points, it's very easy to manually apply operations to the entire dataset. However, good datasets are very rarely this small. 

The Pandas library in Python allows us to use **vectorised operations** (i.e. operations across multiple data points simultaneously), making it much easier to **work with large amounts of data**.

In this train, we look at how to **manipulate data within DataFrames**. 

Let's start by **importing** the **Pandas library** and the **dataset**.

In [1]:
import pandas as pd
import numpy as np

**Note:** A new version of the Pandas package, `Pandas 2`, was released in April 2023. While it comes with added functionality, we continue to use `Pandas 1` in this train for stability purposes.

In [2]:
# Load data - pass 'Name' as our index column.
df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/fundamentals/football_players.csv', index_col='Name')

# Use the head() function to look at the first 5 rows.
df.head()

C:\Users\jeanm\AppData\Local\Temp\ipykernel_86792\3842239110.py:2: DtypeWarning: Columns (14,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/fundamentals/football_players.csv', index_col='Name')

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
Cristiano Ronaldo,32,Portugal,94,89,63,89,63,93,95,85,...,83,94,23,91,92,31,80,85,88,ST LW
L. Messi,30,Argentina,93,92,48,90,95,95,96,77,...,88,85,26,87,73,28,59,90,85,RW
Neymar,25,Brazil,92,94,56,96,82,95,92,75,...,81,80,33,90,78,24,53,80,83,LW
L. Suárez,30,Uruguay,92,88,78,86,60,91,83,77,...,83,87,38,77,89,45,80,84,88,ST
M. Neuer,31,Germany,92,58,29,52,35,48,70,15,...,55,25,11,61,44,10,83,70,11,GK

## Sorting

One basic operation to perform when working with a large dataset is to **sort the values using some criteria**. 

For DataFrames, sorting can be achieved by using the `sort_values()` function. To **sort** data entries **by a specific column(s)**, we need to pass the column(s) to the function. 

Let's look at some examples:

### Example 1a

In [ ]:
# Sort by age from youngest to oldest (select first 5 entries).
df.sort_values(by='Age').head()

### Example 1b

In [ ]:
# Sort by age from youngest to oldest (select first 5 entries), then by Overall, also ascending.
df.sort_values(by=['Age', 'Overall']).head()

### Example 2

When sorting values, the default option sorts data in ascending order. If we want to sort in descending order, we need to pass in the parameter `ascending=False`.

In [ ]:
# Sort by age from oldest to youngest (select first 5 entries).
df.sort_values(by='Age', ascending=False).head()

## Filtering

Another useful thing to do with a DataFrame is to filter the values to **only view the data we are interested in**. 

If we **pass in any condition inside the square brackets** after the DataFrame name, we filter out rows that fail to meet that condition. For example, the command `df['Age' > 30]` returns a boolean series containing the players' names (the index for our DataFrame) and whether the age is above 30 or not. When this is used to filter on our original DataFrame, it returns only rows that meet the condition.

### Example 3

In [ ]:
# Filter on players older than 30.
df[df['Age'] > 30]

### Example 4

We can also **pass multiple conditions** in the square brackets by using the `|` and `&` operators. 

**Note:** Each condition should be closed inside round brackets as well.

In [ ]:
# Filter on players older than 30 and overall rating greater than 90.
df[(df['Age'] > 30) & (df['Overall'] > 90)]

## Creating columns

We can **create new columns from existing** columns in a Pandas DataFrame. 

We simply **define the new column name** as a string inside square brackets, followed by an `=` sign, and then the **function or operation** applied to the existing column(s).

### Example 5

In [ ]:
# Create a column of rating per year of age.
df['Rating Per Year of Age'] = df['Overall'] / df['Age']

# Look at the first 5 entries.
df['Rating Per Year of Age'].head()

## Deleting columns

Columns can be deleted using the `drop()` function. 

The arguments are the **column name** and the **axis** which should be:
- **1** if we are deleting **columns.**
- **0** if we are deleting **rows**.

### Example 6

In [ ]:
# Drop the column we just created in Example 5
df = df.drop('Rating Per Year of Age', axis=1)

df.head()

## Grouping data

We can also **group** the data in a DataFrame **according to desired criteria**. 

Grouping in DataFrames can be achieved using the `groupby()` function. 

Depending on our application, we **may need to call an aggregation function** for the grouped data after the `groupby()` function call. Examples of aggregation functions include `mean()`, `sum()`, `min()`, and `max()`. This will result in **a column of values from the chosen aggregation** (for numeric columns).

### Example 7

In [3]:
# Let's look at the average rating by age (first 5 rows).
df.groupby('Age')[['Overall']].mean().head()

       Overall
Age
16   57.846154
17   56.089147
18   57.287202
19   59.430309
20   61.559839

### Example 8

It is possible to **group by more than one column**. We simply need to pass the list of columns.

In [4]:
# Look at the average rating by age and nationality (first 15 rows).
df.groupby(['Age', 'Nationality'])[['Overall']].mean().head(15)

                   Overall
Age Nationality
16  Argentina    56.000000
    England      61.500000
    France       54.000000
    Germany      57.000000
    Italy        61.000000
    Netherlands  62.000000
    Norway       54.500000
    Romania      54.000000
    Spain        58.000000
17  Algeria      54.000000
    Argentina    57.333333
    Australia    52.000000
    Austria      54.500000
    Belgium      58.250000
    Canada       56.000000

## Transforming data

It is often the case that we want to **format columns inside our DataFrame**. 

We can transform a column using the `apply()` function, while we use the `map()` function to transform multiple columns at once. We can create a function by using `def` or `lambda`.

### Example 9

**a) Apply a custom function to a DataFrame**

To format a column in our dataset, we start by creating the function.

In [ ]:
# Using def to create a custom function.
def year_to_month(x):
    "Converts no of years to no of months"
    return x * 12

We then apply the function to the intended column.

In [ ]:
# Change the age column to months and look at the first 5 entries.
df['Age'].apply(year_to_month).head()

### Example 10

**b) Using a lambda function on a DataFrame**

We can also use a lambda function and apply it to the DataFrame. A lambda operator or lambda function is used for **creating small, one-time, anonymous function objects** in Python. 

**Basic syntax:**

```python
lambda [arguments]: [expression]
```

Lambda operators can have any number of arguments, but they can have **only one expression**. It cannot contain any  `print` or `raise` statements, and it returns a function object which can be assigned to any variable.

In [ ]:
# Using a lambda operator.
year_to_month_lamb = lambda x: x * 12

In [ ]:
# Print function answer.
print('def: ', year_to_month(30))
print('lambda: ', year_to_month_lamb(30))

In the example above, we can see that both function versions, `def` and `lambda`, produce the same output. The difference is that the `lambda` can only have a single expression and does not need to return anything.

Let's use the lambda function to format a column in our dataset:

In [ ]:
# Change the age column to months and look at the first 5 entries.
df['Age'].apply(lambda x: x*12).head()

### Example 11

Let's try to create a function that creates a column with the **player position type**, where types can be `Forward`, `Midfielder`, `Back`, or `GoalKeeper`.

In [ ]:
# Create function.
def position_type(s):
    
    """"This function converts the individual positions (abbreviations) and classifies it
    as either a Forward, Midfielder, Back, or Goalkeeper"""
    
    if (s[-2] == 'T') | (s[-2] == 'W'):
        return 'Forward'
    elif s[-2] == 'M':
        return 'Midfielder'
    elif s[-2] == 'B':
        return 'Back'
    else:
        return 'GoalKeeper'

In [ ]:
# Create position type column.
df['Preferred Positions Type'] = df['Preferred Positions'].apply(position_type)

# Look at the first 5 entries.
df['Preferred Positions Type'].head()

### Example 12

Let's create another function to transform many columns at once using the `map()` function. 

Before we go on, a lot of the columns look like they should be numerical but are actually stored as a string. We can check this by using the `info()` function:

In [ ]:
df.info()

As we can see, most of the number columns (attributes) are stored as strings (objects).

We will create a function that:
- Transforms all the supposedly **numeric columns to a float**.
- For the string-number columns, we will only select and **transform the first two digits** before the comma.

In [ ]:
# Select all numeric attribute columns, i.e. excluding "word-type" columns such as Nationality.
cols = ['Overall', 'Acceleration', 'Aggression',
       'Agility', 'Balance', 'Ball control', 'Composure', 'Crossing', 'Curve',
       'Dribbling', 'Finishing', 'Free kick accuracy', 'GK diving',
       'GK handling', 'GK kicking', 'GK positioning', 'GK reflexes',
       'Heading accuracy', 'Interceptions', 'Jumping', 'Long passing',
       'Long shots', 'Marking', 'Penalties', 'Positioning', 'Reactions',
       'Short passing', 'Shot power', 'Sliding tackle', 'Sprint speed',
       'Stamina', 'Standing tackle', 'Strength', 'Vision', 'Volleys']

In [ ]:
# Create function.
def to_float(x):    
    "Transforms numeric attribute columns to type float"
    
    if type(x) is int:
        return float(x)
    else:
        return float(x[0:2])

In [ ]:
# Use the map() function to transform all selected columns.
df[cols] = df[cols].map(to_float)

Now let's look at the data types of the columns:

In [ ]:
df.info()

We can see that the columns have been transformed to the `float` type successfully.

#  

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/refs/heads/master/ALX_banners/ALX_Navy.png"  style="width:140px";/>
</div>